### ISSUE TITLE
Issues Blacklisting by Domain (Deadwood)

### ISSUE THREAD

**Issue by AoifeGallagher** [samboy/MaraDNS#10]
Hi,

I am having trouble blacklisting by domain using Deadwood. I want to be able to store a list of blacklisted domains in a separate file (blacklist.txt). In my dwood3rc.txt I have a line:

 execfile("C:\MaraDNS\maradns-2-0-11-win32\Deadwood-3-2-07-win32\execfile\blacklist.txt").

My blacklist.txt consists of:

 upstream_servers = {}
upstream_servers["Facebook.com."]="10.254.254.254"

Deadwood compiles fine and no errors in dwlog.txt, I also deleted dw_cache_bin after making changes. I can still however browse to Facebook.

Any help in getting this working would be greatly appreciated.

Thanks

**Comment by samboy** [comment]
Documented: In UNIX and UNIX clones, execfile files need to be in /etc/deadwood/execfile/

Undocumented: In Windows, execfile files need to be in the same directory as deadwood.exe

Documented: Execfile filenames can only have lower-case letters and the underscore character ("_")

To correctly purge the cache after changing the dwood3rc file:

* Stop Deadwood (the Deadwood service in Windows)
* Remove the dw_cache (dw_cache_bin in Windows file)
* Edit the dwood3rc file as needed.
* Start Deadwood 

I actually tried to make this a little more convenient at one point, but it became more bother than it was worth.

Closing: If you still have issues with this, leave a comment and I will respond.

**Comment by AoifeGallagher** [comment]
Hi Sam,

I am still having some issues here. I followed your steps here as well as this link http://maradns.samiam.org/deadwood/doc/execfile-HOWTO.html.

In my dwood3rc.txt (located: C:\MaraDNS\maradns-2-0-11-win32\Deadwood-3-2-07-win32) I have:
							
upstream_servers = {}
execfile("blacklist")

In my blacklist.txt (located: C:\MaraDNS\maradns-2-0-11-win32\Deadwood-3-2-07-win32):

upstream_servers["Facebook.com."] = "10.254.254.254"

I stopped the service deleted the dw_cache_bin and made the changes etc then restarted. I can still browse to facebook. I also tried ipconfig/flushdns and clearing my history in case that was affecting it but no luck. Again I really appreciate the help.

Thanks

**Comment by samboy** [comment]
You can't have the "." in the filename that execfile() points to. Just name the file something like "blacklist" (no ".").  If you need the file extension to edit it, have another file called blacklist.txt and then have a "blacklist.bat" file with this line in it:

```
copy blacklist.txt blacklist
```

Click on the blacklist.bat file to copy over the revised blacklist for Deadwood to use.

**Comment by AoifeGallagher** [comment]
That worked perfect, thanks a million, I really appreciate it.
