### ISSUE TITLE
dig AXFR query returns "Question section mismatch"

### ISSUE THREAD

**Issue by 0x4d4c** [samboy/MaraDNS#11]
Hi,

when I execute
```
dig @some-nameserver some.domain.xyz AXFR
```
I get the output
```
;; Question section mismatch: got some.domain.xyz/SOA/IN
```
```drill``` and ```fetchzone``` work as expected.

I know that this issue has been discussed on the mailing list back in 2011 (I think), but I still get this error with maradns-2.0.09 (the Ubuntu package) as well as with maradns-Q.2015-02-07.1 (compiled from source).

Is it a problem of maradns or dig?

**Comment by samboy** [comment]
You know, it would be really nice if the ISC would stop breaking Dig. For years, Dig could care less if the question in an AXFR reply reflected the original AXFR query. They had no good reason to change the behavior. Well, yeah, they made RFC5936 to justify breaking Dig. There's a reason DJB complained loudly the first time they tried making an AXFR RFC, and why I completely supported DJB on that matter.

Anyway, I've patched the zoneserver program to be RFC5936 compliant enough for Dig to be happy with it again. Get it here with that newish Git program everyone is now using: 

```bash
git clone https://github.com/samboy/MaraDNS 
```
Another thing: Deadwood was declared feature complete on July 22, 2010. I ignore any and all RFCs written after that date unless there's a lot of money on the table; non-DNSSEC DNS worked fine on that day and no one is paying me enough to play the "let’s break DNS with new RFCs" game. 

Closing but leaving comments open. Let me know if you still have problems.

**Comment by 0x4d4c** [comment]
I've tested Dig version 9.8.4 with MaraDNS from Git (the state it had today) and everything is working fine for me now.

Understanding your point of view on feature completeness and the "let's break DNS with new RFCs game" as you called it, I really appreciate fixing this so quickly. So, thank you very much!
