### ISSUE TITLE
Deadwood doesn't send DNS-request over TCP protocol

### ISSUE THREAD

**Issue by ooligo4** [samboy/MaraDNS#12]
I've set "tcp_listen = 1" in dwood3rc.txt, stoped and started service. But as I can see in sniffer (http://download.microsoft.com/download/7/1/0/7105C7FF-768E-4472-AFD5-F29108D1E383/NM34_x86.exe) all DNS-requests are still sent by UDP protocol.

**Comment by samboy** [comment]
Yep, as per design. Deadwood is first and foremost a UDP DNS name server. While I was developing Deadwood (Between October 5, 2007, and July 22, 2010, when Deadwood/MaraDNS 2 was feature complete), the RFCs said that DNS-over-TCP was optional.

RFC 5966, which mandates DNS-over-TCP, came out in August of 2010, after I declared Deadwood feature complete. I am ignoring RFCs that came out after July of 2010; no one is paying me enough money to play the "break DNS with new RFCs" game. 

That said, one can get some more replies over TCP with Deadwood by adding this line to the dwood3rc file:

```
truncation_hack = 0
```

Only do this if using upstream_servers; this will break some replies if using root_servers (or if neither root_servers nor upstream_servers are set).

Closing, but leaving comments open.
