### ISSUE TITLE
Unable to use new style domain names

### ISSUE THREAD

**Issue by Chealion** [samboy/MaraDNS#13]
When attempting to create a zone using a newer style domain name (eg. .bike) maradns complains about it being a bad zone file:

    etc_maradns_mararc[22765]: Bad zone name mydomain.bike (don't forget the trailing dot!)

**Comment by Remmy** [comment]
Hi Chealion, can you show us the relevant line from your mararc in which you try to load this zone?

**Comment by Chealion** [comment]
And I was missing the trailing dot after the tld in the mararc file. Sorry.

Editing and redoing the actual zone had nothing to do with it all along. (Where I had previously gotten this error due to the trailing dot.)

Thanks!

**Comment by Remmy** [comment]
> And I was missing the trailing dot after the tld in the mararc file.

That's what I thought! Glad you got it fixed :-)
