### ISSUE TITLE
Have Deadwood-HOWTO be a full tutorial

### ISSUE THREAD

**Issue by tfarina** [samboy/MaraDNS#14]
I'm trying to setup a dns server on my home network, but dnsmasq isn't working out of the box. So I'm looking for alternative solutions.

**Comment by Remmy** [comment]
Thiago Farina schreef op 2015-04-27 20:41:
> I'm trying to setup a dns server on my home network, but dnsmasq isn't
> working out of the box. So I'm looking for alternative solutions.

Hi Thiago,

What are you trying to accomplish? What is the envisioned role of 
maradns and what that of dnsmasq in what you are trying to do?

Using maradns (or deadwood) as recursive nameserver for your home 
network should not be any problem at all.

**Comment by samboy** [comment]
I think the original poster's issue is that there really isn’t more “How do I get started?” documentation for Deadwood.  There *is* a HOWTO, but it’s pretty terse:

http://maradns.samiam.org/deadwood/doc/Deadwood-HOWTO

It would be nice if the getting started guide was as extensive as Deadwood’s installation guide:

http://maradns.samiam.org/deadwood/doc/INSTALL.txt

I will keep this bug open; I might even get around to fleshing out the Deadwood HOWTO (and adding notes on configuring and running Deadwood to the INSTALL doc) sometime this month.

**Comment by samboy** [comment]
MOD: I am changing the title of this bug to clarify that it won't be closed until the Deadwood-HOWTO is more than three terse examples.

**Comment by samboy** [comment]
Based on the comments in https://github.com/samboy/MaraDNS/issues/22 some things I need to add:

* Explain to Windows user to not use nslookup, but to use Askmara or Digg instead
* Explain that, on a slow connection, increasing timeout_seconds helps
* Explain that, on an unreliable connection, having a timeout_seconds of 1 and a high max_retries is best
* Explain that Deadwood will not magically make a lousy, unreliable DNS server (or proxy like Dnscrypt which appears to be quite flaky) work better.
* Explain that Deadwood, when running as a fully recursive server, will be slower than a recursive server on a fast network (like Google’s 8.8.8.8)

**Comment by samboy** [comment]
This bug has been open for over a year. Time to accept I just won’t be able to make time to write up yet another Deadwood tutorial.

Welcome to the world of open source economics: The code is free, but there is no guarantee of support, since there is no money on the table compelling one to support the program.
