### ISSUE TITLE
Tilde (~) in spf record

### ISSUE THREAD

**Issue by kpietru** [samboy/MaraDNS#15]
Maybe bug.

Config_1 with "~ all"
```
[...]
example.com.      TXT  'v=spf1 a mx ptr ip4:XX.X.XX.XXX ~all' ~
[...]
```

DNS Checker: http://mxtoolbox.com/domain/example.com
SPF: "No records found"

Config_2 with "- all"
```
[...]
example.com.      TXT  'v=spf1 a mx ptr ip4:XX.X.XX.XXX -all' ~
[...]
```

DNS Checker: http://mxtoolbox.com/domain/example.com
SPF: "OK"

This record passes validation on the server bind9.
Bug?

System: Ubuntu 14.04 maradns_2.0.09-3

**Comment by Remmy** [comment]
Thank you for your report.

It could just as well be a bug in the website you used instead of in 
maradns.

To verify, please use the following command:

askmara Zexample.com.

It should give you (among others) the SPF record. If not, please respond 
with the unredacted output this tool gives you for both of these cases 
(both ~all and -all).

**Comment by kpietru** [comment]
Result command askmara ...
```
root@server:/# askmara example.com
# Querying the server with the IP 127.0.0.1
# Hard Error: Timeout
```
```
root@server:/# askmara unredacted example.com
# Hard Error: Malformed IP
```

Config /etc/maradns/db.example.com
```
example.com. SOA ns1.example.com. admin@example.com. 2015060201 7200 3600 1209600 1800 ~

example.com. NS ns1.example.com. ~
example.com. NS ns2.example.com. ~

ns1.example.com. A XX.X.XX.XXX ~
ns2.example.com. A XX.X.XX.XXX ~

example.com.      A XX.X.XX.XXX ~
www.example.com.  A XX.X.XX.XXX ~

example.com.      MX 10 mail.example.com. ~
mail.example.com. A     XX.X.XX.XXX       ~
example.com.      TXT  'v=spf1 a mx ptr ip4:XX.X.XX.XXX ~all' ~
```

Config /etc/maradns/mararc
```
[...]
# We must initialize the csv1 hash, or MaraDNS will be unable to
# load any zone files
csv1 = {}
csv2 = {}

# This is just to show the format of the file
# csv1["example.com."] = "db.example.com"
csv2["example.com."] = "db.example.com"

# The address this DNS server runs on.  If you want to bind
# to all addresses a given machine has, use "0.0.0.0".
bind_address = "XX.X.XX.XXX,127.0.0.3"
[...]
```

Where "XX.X.XX.XXX" is my IP and "example.com" is my domain.

**Comment by Remmy** [comment]
You must put the Z directly in front of the domain name:

askmara Zexample.com

As it seems your system is not set up to answer queries from localhost, 
you can query another nameserver, for example the free one of google:

askmara Zexample.com 8.8.8.8

Where I wrote 'unredacted', I meant for you to show the output without 
changing domain name or obscuring IP-addresses.

**Comment by kpietru** [comment]
```
root@server:/# askmara Zexample.com.
# Querying the server with the IP 127.0.0.1
# Hard Error: Timeout
```

```
root@server:/# askmara Zexample.com. 8.8.8.8 
# Querying the server with the IP 8.8.8.8
# Question: Zexample.com.
example.com. +21599 ns ns1.example.com.
example.com. +21599 ns ns2.example.com.
example.com. +21599 soa ns1.example.com. admin@example.com. 2015060202 7200 3600 1209600 1800
example.com. +21599 a XX.X.XX.XXX
example.com. +21599 mx 10 mail.example.com.
# NS replies:
# AR replies:
```


Where "XX.X.XX.XXX" is my IP and "example.com" is my domain.



Original but today I will remove this part.
```
root@server:/# askmara Zlokolab.net. 8.8.8.8 
# Querying the server with the IP 8.8.8.8
# Question: Zlokolab.net.
lokolab.net. +21599 ns ns1.lokolab.net.
lokolab.net. +21599 ns ns2.lokolab.net.
lokolab.net. +21599 soa ns1.lokolab.net. kpietru@poczta.fm. 2015060202 7200 3600 1209600 1800
lokolab.net. +21599 a 31.6.70.233
lokolab.net. +21599 mx 10 mail.lokolab.net.
# NS replies:
# AR replies:
```

**Comment by Remmy** [comment]
On the original for lokolab, is this the version with ~all ? Can you also show the same for -all?

**Comment by kpietru** [comment]
I changed the setting to "- all".
Now:
```
root@server:/# askmara Zexample.com. 8.8.8.8 
# Querying the server with the IP 8.8.8.8
# Question: Zexample.com.
example.com. +20042 ns ns1.example.com.
example.com. +20042 ns ns2.example.com.
example.com. +20042 soa ns1.example.com. admin@example.com. 2015060202 7200 3600 1209600 1800
example.com. +20042 a XX.X.XX.XXX
example.com. +20042 mx 10 mail.example.com.
# NS replies:
# AR replies:
```
```
root@server:/# askmara Zexample.com.
# Querying the server with the IP 127.0.0.1
# Hard Error: Timeout
```

And now:
http://mxtoolbox.com/domain/example.com/


Please edit your post and remove the word "lokolab". Thanks.

**Comment by Remmy** [comment]
Sorry, but I can't help you if you keep reverting to a domain name you 
don't control (example.com).

Also, the general idea of having DNS for a domain you control is so it 
can be accessed by others on the internet. I don't see any sensitive 
information in the snippets you've provided.

**Comment by kpietru** [comment]
Ok.

**Comment by kpietru** [comment]
I wanted to protect. For now, the server configuration is "raw".

**Comment by kpietru** [comment]
A few days later ...
This is my valid SPF record. Why is not valid in MaraDNS?
```
[...]
example.com.      TXT  'v=spf1 a mx ptr ip4:XX.X.XX.XXX ~all' ~
[...]
```

Here is my problem:
Source https://github.com/samboy/MaraDNS/blob/master/parse/Csv2_rr_txt.c#L437 line 437
```c
                               } else if(look == '~') {
                                        csv2_error(stream,
                           "The ~ character is not allowed in TXT records\n"
                           "Please use the '\\x7e' escape sequence instead.\n"
                           "man csv2_txt for more information");
                                        return 0;
                                } else if(look == 127) {
```


I turned on the logs in MaraDNS (verbose_level = 3).
Log /var/log/syslog:
```
Jun  3 19:37:10 server etc_maradns_mararc[3758]: Error: The ~ character is not allowed in TXT records
```

I changed the sign "~" to "'\x7e'". Now MaraDNS works perfectly.
```
example.com.      TXT  'v=spf1 a mx ptr ip4:XX.X.XX.XXX '\x7e'all' ~
```

**Comment by samboy** [comment]
MOD: I have updated the title to be "Tilde (~) in spf record".

There are a couple of ways the issue with tildes in SPF records can be figured out:

* Look at the logs MaraDNS generates. In the logs, it will tell you to use '\x7f' instead of a tilde
* Go to http://maradns.samiam.org/search.html and search for "SPF".  The first result says to perform "man csv2_txt" to find the solution to the problem.

That said, there are a couple of areas where I should have this note, since two different people were scratching their head about this issue in this thread:

* I will add a note to http://maradns.samiam.org/faq.html#spf
* I will update the csv2 man page to have a note about how to put tildes in SPF records

That said, while it seems fair

**Comment by samboy** [comment]
Note added to FAQ and csv2 man page. Closing.
