### ISSUE TITLE
Doesn't install properly on latest Mac OS X

### ISSUE THREAD

**Issue by Zero3K** [samboy/MaraDNS#27]
Its trying to install to directories that don't exist. Maybe you could either point the makefile to the proper directories or have it make them.

**Comment by samboy** [comment]
You buying me a Mac? I don’t have one. The only operating systems I support are Windows 7 and CentOS 6.

If you want me to fix it, give me a 13" Retina Macbook Pro with a 2.9ghz processor, 512 gigs of storage, and right gigs of ram.

**Comment by Zero3K** [comment]
Btw, I managed to get it to work properly on a Pandora (http://www.openpandora.org). It just required creating some directories, changing permissions, making a script that passes my root password to sudo which is used to run it and adding it to the startup list used by XFCE. So, it should be able to work on Mac OS X by doing the same things.

**Comment by samboy** [comment]
This is the message you got when you typed in configure:

WARNING WARNING WARNING

This is an unknown platform.  MaraDNS may or may not compile on this platform.  If you are able to sucessfully compile and install MaraDNS on this platform, please let me know by filing a Github issue.

I encourage you to make a fork of MaraDNS for this platform so other users may not see this obnoxious warning.

I ask that any fork of MaraDNS not be called "MaraDNS"

**Comment by Zero3K** [comment]
Ok.

**Comment by samboy** [comment]
Thanks. If someone were to buy me a nice 13 inch retina MacBook, I would probably be able to find time to properly get it to work in MacOS. Until then, what I did last time I had a Mac was to just copy the files by hand; for Deadwood (the imperfect recursive resolver), directions are at https://github.com/samboy/MaraDNS/blob/master/deadwood-github/INSTALL.txt

Clumsy, but works.
