### ISSUE TITLE
possible deadwood bug

### ISSUE THREAD

**Issue by ktrace** [samboy/MaraDNS#32]
Good day!

gentoo, maradns-2.0.09-r2, Deadwood not reply at all.

dwood3rc:
```
bind_address="127.0.0.1, 192.168.0.2"
chroot_dir = "/etc/maradns" # Directory we run program from (not used in Win32)
upstream_servers = {}
upstream_servers["."] = "8.8.8.8"
recursive_acl = "127.0.0.1/8, 192.168.0.0/16, 172.16.0.128/25" # Who is allowed to use the cache
resurrections = 1
verbose_level = 200
```
is it bug?

**Comment by samboy** [comment]
The supplied dwood3rc file works for me in CentOS6. Please be sure to follow all of the steps here to install Deadwood: https://github.com/samboy/MaraDNS/blob/master/deadwood-github/INSTALL.txt

Closing this bug.
