### ISSUE TITLE
WONTDO: Please support CAA records (record type 257)

### ISSUE THREAD

**Issue by TheGroundZero** [samboy/MaraDNS#35]
From: [CAA Mandated by CA/Browser Forum](https://blog.qualys.com/ssllabs/2017/03/13/caa-mandated-by-cabrowser-forum)

CAA creates a DNS mechanism that enables domain name owners to whitelist CAs that are allowed to issue certificates for their hostnames. It operates via a new DNS resource record (RR) called CAA (type 257). Owners can restrict certificate issuance by specifying zero or more CAs; if a CA is allowed to issue a certificate, their own hostname will be in the DNS record. For example, this is what someone’s CAA configuration could be (in the zone file):

`example.org. CAA 128 issue "letsencrypt.org"`

In addition to the “issue” directive from the example, two other directives are supported: “issuewild” that restricts issuance of wildcard certificates, and “iodef”, which provides support for notification in the cases something goes wrong.  
The number “128” is a flags byte with its highest bit set, meaning the directive use is considered critical and must be followed.

**Comment by samboy** [comment]
MaraDNS was frozen in August of 2010, and I have no plans to support anything which comes from a RFC more recent than that at this time. (RFC6844 is from January of 2013)

The RAW record type can be used to support CAA, or for that matter, any other kind of record. See http://maradns.samiam.org/tutorial/man.csv2.html for details.

**Comment by samboy** [comment]
I am open to accepting a pull request, as long as the code is clean and appears bug-free (since I’m the one who gets to fix bugs after accepting the pull request)

**Comment by TheGroundZero** [comment]
I'd expect the following line to add the CAA record to my domain, however this doesn't seem to work, at least SSLlabs reports that the DNS entries aren't there for the domain.

    example.com.            RAW 257 '128 issue "letsencrypt.org"' ~
    example.com.            RAW 257 '128 iodef "hostmaster'\x40'example.com"' ~

**Comment by samboy** [comment]
Use Askmara to see how unknown record types would look in a zone file, e.g.

```
$ askmara 257:google.com. 8.8.8.8
# Querying the server with the IP 8.8.8.8
# Question: Ugoogle.com.
google.com. +86399 raw 257 \x00\x05'issuepki.goog'
google.com. +86399 raw 257 \x00\x05'issuesymantec.com'
# NS replies:
# AR replies:
```

**Comment by TheGroundZero** [comment]
OK, managed to get it to work using the weird looking syntax

    example.com.            RAW 257 \x00\x05'issueletsencrypt.org' ~

    askmara 257:example.com. 8.8.8.8
    example.com. +86254 raw 257 \x00\x05'issueletsencrypt.org'

    dig @8.8.8.8 example.com caa
    example.com.         86399   IN      CAA     0 issue "letsencrypt.org"

Thanks a lot for the help!
