### ISSUE TITLE
WONTDO: Support multiple custom ports for Deadwood upstream servers

### ISSUE THREAD

**Issue by ghost** [samboy/MaraDNS#39]
Hi,

Currently Deadwood only allows one custom port for all upstream servers via `upstream_port`. Would you please add support for multiple custom ports for upstream servers?

For example:

```python
upstream_servers["example.com."] = "127.0.0.1:5353"
```

Thank you,

**Comment by samboy** [comment]
The nice thing about open source is that anyone can look at the source code and implement the features they want to. I am not implementing new features for MaraDNS without getting paid at this time -- but with the source code, anyone else is free to implement it.

Use the source, Luke. Make it happen.

**Comment by samboy** [comment]
I am locking this as “off-topic”: https://maradns.samiam.org clearly states “MaraDNS is in deep freeze — I only fix security and other serious bugs”, and the README.md for MaraDNS clearly states “I am declaring MaraDNS finished: While I will still fix important security bugs in MaraDNS, and will probably still fix other critical bugs, I currently have no plans to add new features to MaraDNS.” 

I have had multiple people, when I tell them no, you’re not paying me, respond with “but could you make and exception”, “it won’t be that much work”, “more people would use MaraDNS”, blah blah blah. NO MEANS NO and I don’t want to waste my time getting in to a discussion where some random Internet anonymous identity keeps not accepting my no. 

I have put up a boundary. It is too bad people on the Internet often times do not have the simple courtesy to accept it.
