### ISSUE TITLE
Are these bugs?

### ISSUE THREAD

**Issue by Loggy48** [samboy/MaraDNS#40]
1. I had to add authbind and set /etc/authbind/byuid/nn to 0.0.0.0/53/53 to get maraDNS to work, as otherwise when it chroot's to maradns, it cannot bind to port 53.

2. Zoneserver runs under UID 99 rather than migrating also to maradns, although TCP requests are probably rare.

**Comment by samboy** [comment]
Both of these bugs are Debian-specific issues (remember, Ubuntu and all Ubuntu forks are derivatives of Debian). To file a Debian bug, please follow the directions here: https://www.debian.org/Bugs/Reporting

I am not getting paid enough to support Debian issues. While I would love to be able to buy a yacht and a private jet airplane with the money MaraDNS makes, MaraDNS does not make that kind of money — actually, it is a net loss for me at this point.  While I’m not entitled to my own MaraDNS Gulfstream V Jet, I am also not required to give anyone free MaraDNS support either.
