### ISSUE TITLE
Deadwood bug: secret.txt opened in text mode on Windows

### ISSUE THREAD

**Issue by jojothe** [samboy/MaraDNS#51]
After using Deadwood on Windows successfully for years (and loving it!), I got this error when I installed it on a new machine:

Friday, November 30, 2018 17:12:22 PM: Unable to get 128 bits of entropy; file secret.txt must be
 at least 16 bytes (128 bits) long

It turns out mkSecretTxt.exe happened to put a control-Z in the first 16 bytes of secret.txt, and the file is opened in text mode (O_RDONLY), so Windows reads the control-Z as EOF and thinks the file is too short.  (I worked around it by re-running mkSecretTxt.exe to get a secret.txt with no control-Z.)

A better fix, in get_entropy_from_seedfile():
        seed = open(filename, O_RDONLY|O_BINARY);

**Comment by samboy** [comment]
`O_BINARY` is a Windows-specific option, so I had to put the code in a `#ifdef MINGW` block

**Comment by samboy** [comment]
Looks like that will work, but, yes, `O_BINARY` will *not* compile in Linux.  See https://sourceforge.net/p/mingw/bugs/1396/

**Comment by samboy** [comment]
I have fixed the issue and have committed the code. I will close this ticket when I make a new Deadwood tarball (and, yes, Windows binary zipfile) with the updated code.

**Comment by samboy** [comment]
Snapshot Deadwood with this fix made:  https://maradns.samiam.org/Deadwood/snap/

Next:

* Run automated SQA tests on snapshot to ensure no regressions were introduced
* Once the SQA suite passes, compile and make Windows binary
* Make sure Windows does not Ctrl+Z issue
* Make Deadwood 3.2.14 release (Source, Windows binary) with updated code

**Comment by samboy** [comment]
The 2019-01-16 snapshot passes all SQA regression tests; no regressions were introduced.

**Comment by samboy** [comment]
I have made a test compile in Windows.  The test compile is able to start and resolve domains with a `secret.txt` consisting of nothing but `^Z` (ASCII code 26); to verify this fixes the bug, Deadwood 3.2.12 is unable to resolve domains with the same `secret.txt` file.

Next: Release Deadwood 3.2.14

**Comment by samboy** [comment]
Deadwood 3.2.14 released.  No changes except this bugfix.  Available for download:

* [https://maradns.samiam.org/deadwood/stable/](https://maradns.samiam.org/deadwood/stable/)
* [https://sourceforge.net/projects/maradns/files/Deadwood/3.2.14/](https://sourceforge.net/projects/maradns/files/Deadwood/3.2.14/)

Closing ticket.

**Comment by samboy** [comment]
I will make a MaraDNS 2.0.17 release with Deadwood 3.2.14 once I have a fix for https://github.com/samboy/MaraDNS/issues/52 available.

Also, this is not a security problem because Deadwood refuses to run if it does not have a safe level of entropy (128 bits or more).

**Comment by samboy** [comment]
Locking conversation to avoid spam.
