### ISSUE TITLE
Memory exhaustion (possibly FreeBSD-specific?)

### ISSUE THREAD

**Issue by njogun** [samboy/MaraDNS#52]
Hi Sam,

Long term happy MaraDNS user here - thanks!

After latest updates to the OS and MaraDNS I started experiencing consistent crashes of MaraDNS with the default config (specifically with no max_mem parameter in mararc) giving the following error:
`Dec 28 12:58:31 srv /usr/local/sbin/maradns: Aieeeeee, can not allocate memory!`

I set max_mem to 8MB in my config as a workaround which seems to resolve the issue for me. Hence this is not a support request (and is likely specific to FreeBSD which is not a supported platform anyway - happy for the issue to be closed if so). However, I wanted to report it here for your perusal in case there is more to it.

I have provided technical details in FreeBSD bug report (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=234494).

**Comment by samboy** [comment]
Changing the default for 2019 should be a one-line fix, and I would be happy to do that. The old value for max_mem is from 12 years ago, when computers came with about 512 megs of memory and maxed out at two gigabytes. I’ll probably make it 16mb, along with a note for people still using things like $15/year 128mb OpenVZ virtual machines.

**Comment by samboy** [comment]
Here is the actual code in question in MaraDNS.c:

```
    maxprocs = read_numeric_kvar("max_mem",
               1048576 + thread_overhead +
               ((cache_size + dns_records_served) * 1536));
```

The final argument is the default value; I can easily double those in this day and age of 64-bit servers.

**Comment by samboy** [comment]
I have fixed the issue and have committed the code. I will close this ticket when I make a new MaraDNS tarball with the updated code.

**Comment by njogun** [comment]
Hi Sam,

Thanks for looking into this issue and appreciate the fix.

P.S. 
I saw you made some documentation updates so I thought I would mention that a few places describe max_mem setting to be in kilobytes e.g. parse/ParseMaraRc.c (lines 141-142)
```
        "max_mem", /* The maximum amount of memory we allow MaraDNS to
                    * allocate, in kilobytes */
```
More importantly man page is correct.

**Comment by samboy** [comment]
Done. Let me know if there is anywhere else where this memory is incorrectly labeled “kilobytes”.

**Comment by samboy** [comment]
MaraDNS 2.0.17 tarball made:

* http://maradns.samiam.org/download/2.0/2.0.17/
* https://sourceforge.net/projects/maradns/files/MaraDNS/2.0.17/

While I still need to make the Windows binary, update the webpage, and make a formal announcement before MaraDNS 2.0.17 is released, I am closing this ticket.

**Comment by samboy** [comment]
MaraDNS 2.0.17 Windows zipfile made and release announced: https://samiam.org/blog/2019-01-20.html

**Comment by samboy** [comment]
Locking conversation to avoid spam.

**Comment by samboy** [comment]
Ubuntu 20.04’s old version of MaraDNS still has this bug. The workaround is to, if using the Ubuntu-supplied MaraDNS package, to add something like this in the `/etc/maradns/mararc` file:

```
max_mem = 4000000
```

Note that `max_mem` is in *bytes*, not kilobytes (this documentation bug was also fixed over two years ago, but Debian/Ubuntu packages are very slow to update things).
