### ISSUE TITLE
csv2 and csv2_default_zonefile parameters doesn't work (official Deadwood Windows build)

### ISSUE THREAD

**Issue by Geist-zz** [samboy/MaraDNS#57]
I have added two lines to default dwood3rc.txt (found examples in test sources on this github):
csv2 = {}
csv2_default_zonefile = "db.default"

This gives following errors:

csv2 line:
Fatal error in dwood3rc file on line 51 Unknown dwood3rc dictionary parameter

After commenting first csv2 line:
Fatal error in dwood3rc file on line 52 Unknown dwood3rc string parameter

It seems that both parameters aren't recognized by Deadwood.

Deadwood version 3.2.14, official Windows build tested under Windows 7.

**Comment by samboy** [comment]
Deadwood is a recursive, *not* authoritative name server. If you want to use the `csv2` variable, use MaraDNS, *not* Deadwood. If you just want to give a given name a given IP (without being the official authoritative nameserver for the domain in question), use the `ip4` and `ip6` parameters in Deadwood 3.3.03.

**Comment by samboy** [comment]
I have finally fixed the search page to work with Google’s new API at https://maradns.samiam.org/search.html (the old HTML stopped working because of Google changes; perhaps I should use an open source search engine so that pages do not break from the whims of a for-profit company)
