### ISSUE TITLE
performance issues when using certain resolving libraries

### ISSUE THREAD

**Issue by kultakangas** [samboy/MaraDNS#6]
I started using Deadwood in december and I hadn't notice some performance issue until today. BTW i upgraded Deadwood to version 3.2.06. Deadwood listens to 127.0.0.1 and is used by few local programs including spamassassin and my python script which retrieves the reservation data from a certain hotel reservation system. Today i noticed that it takes one minute for the script to login to https://admin.booking.com, which is too slow. Then i commented "nameserver 127.0.0.1" in /etc/resolve.conf and added google public DNS servers instead. The script finished its execution without any noticeable delay.

In order to reproduce the issue i performed the following steps:
1) stopped Deadwood by running /etc/init.d/deadwood stop
2) changed verbose_level to 100 in /etc/dwood3rc
3) removed the /etc/deadwood/dw_cache
4) started Deadwood manually as root
5) executed the following command under the security context of the nobody user: lynx https://admin.booking.com

The problem is that lynx is stuck on the "Looking up admin.booking.com" stage for one minute. When using google public DNS servers, the page is loaded instantly.

Deadwood produces the following output:

Got DNS query for \005admin\007booking\003com\000\000\034
Looking in cache for query \005admin\007booking\003com\000\000\034
Nothing found for \005admin\007booking\003com\000\000\034
Processing NS refer for \005admin\007booking\003com\000\000\034
Processing incomplete CNAME for \005admin\007booking\003com\000\000\034
Caching direct answer at \005admin\001c\007booking\003com\000\000\034
Got DNS query for \005admin\007booking\003com\000\000\034
Looking in cache for query \005admin\007booking\003com\000\000\034
Nothing found for \005admin\007booking\003com\000\000\034
Cached CNAME refer found for \005admin\007booking\003com\000\000\034
Caching direct answer at \005admin\001c\007booking\003com\000\000\034
Got DNS query for \005admin\007booking\003com\000\000\034
Looking in cache for query \005admin\007booking\003com\000\000\034
Nothing found for \005admin\007booking\003com\000\000\034
Cached CNAME refer found for \005admin\007booking\003com\000\000\034
Caching direct answer at \005admin\001c\007booking\003com\000\000\034
Got DNS query for \005admin\007booking\003com\000\000\034
Looking in cache for query \005admin\007booking\003com\000\000\034
Nothing found for \005admin\007booking\003com\000\000\034
Cached CNAME refer found for \005admin\007booking\003com\000\000\034
Caching direct answer at \005admin\001c\007booking\003com\000\000\034
Processing incomplete CNAME for \005admin\007booking\003com\000\000\034
Processing incomplete CNAME for \005admin\007booking\003com\000\000\034
Processing incomplete CNAME for \005admin\007booking\003com\000\000\034
Processing incomplete CNAME for \005admin\007booking\003com\000\000\034
Got DNS query for \005admin\007booking\003com\000\000\001
Looking in cache for query \005admin\007booking\003com\000\000\001
Nothing found for \005admin\007booking\003com\000\000\001
Cached CNAME refer found for \005admin\007booking\003com\000\000\001
Caching direct answer at \005admin\001c\007booking\003com\000\000\001
Looking in cache for query \005admin\007booking\003com\000\000\001
Fetching \005admin\007booking\003com\000\000\001 from cache
Processing incomplete CNAME for \005admin\007booking\003com\000\000\034
Sending SERVER FAIL for query \005admin\007booking\003com\000\000\034

when running "host -t A admin.booking.com 127.0.0.1", the result is returned instantly and the output is  much different (again, Deadwood was stopped, the cache was removed and Deadwood was started again):

Got DNS query for \005admin\007booking\003com\000\000\001
Looking in cache for query \005admin\007booking\003com\000\000\001
Nothing found for \005admin\007booking\003com\000\000\001
Processing NS refer for \005admin\007booking\003com\000\000\001
Processing NS refer for \005admin\007booking\003com\000\000\001
Caching direct answer at \005admin\007booking\003com\000\000\001
Looking in cache for query \005admin\007booking\003com\000\000\001
Fetching \005admin\007booking\003com\000\000\001 from cache

Do you have any idea why the performance is totally different with "lynx" and python's resolving interface? How do you want me to troubleshoot the issue?

Best regards,
Sten Kultakangas

**Comment by samboy** [comment]
Unless you're on an IPV6 network, add this to your dwood3rc file:

```
reject_aaaa = 1
```

I have reproduced your concern and have verified that this resolves it.

What is happening is that your computer is trying to connect to IPv6 IPs, Google's DNS servers are smart enough to not allow IPv6 IPs to resolve over IPv4 connections; with Deadwood, you need to tell it "I am not using IPv6, so don't try to resolve IPv6 addresses".

Another speed up with some connections is to disable reverse DNS (IP to name) lookups:

```
reject_ptr = 1
```

I will add this information to Deadwood's FAQ.

- Sam

**Comment by samboy** [comment]
Closing: reject_aaaa =1 resolves the original poster's issue on my system. Please comment if the issue persists; if so, I will reopen the ticket.

**Comment by samboy** [comment]
Added to FAQ: http://maradns.samiam.org/deadwood/doc/FAQ.html#13
