### ISSUE TITLE
3.4.02: Add Russian (and updated Deadwood-win docs) to tarball tree of MaraDNS

### ISSUE THREAD

**Issue by samboy** [samboy/MaraDNS#63]
Add the Russian translations generously provided by https://github.com/IISergII to the tarball version of MaraDNS (which loosely tracks but is not directly based off of the GitHub tree; perhaps I should someday write a “continuous integration” script which converts a GitHub pull of MaraDNS in to a source tarball and Windows binary via the Mingw cross-compiler).

**Comment by ktrace** [comment]
Hi, Sam!
Not only russian locale not included in tarball on official site: tarballs slightly different. *.tar.gz on GH, *.tar.bz2 on maradns.samiam.org. Different subdirs: maradns-3.4.01/ vs MaraDNS-3.4.01/. For source-based distro (FreeBSD/gentoo) it matters...

**Comment by samboy** [comment]
@ktrace The issue here is that there are currently five sources of truth for MaraDNS’s files:

* The Deadwood source code tarball
* The Deadwood Windows zipfile
* The MaraDNS source code tarball
* The MaraDNS Windows zipfile
* The Git tree of MaraDNS

Right now, when I make a new release of MaraDNS, I have to change one of the sources of truth (make a Git checkin, or make a patch by hand) the apply the change to the other source of truth. There’s also a disconnect between the files in the Windows zipfiles and the same files in the tarballs and Git tree.

This comes from the fact that the MaraDNS codebase was over 13 years old before I added it to GitHub, and I still use both Git and the pre-Git way of updating files with MaraDNS’s.

I hope to have time to, someday, have a more “continuous integration” approach to MaraDNS. This will be a two-step process:

* Take the Git code and make it a MaraDNS and Deadwood source code tarball.
* In a Windows virtual machine, take the MaraDNS/Deadwood source code tarball and make it the MaraDNS and Deadwood zipfiles for the Windows.

However, if I do this, I would not start the process until the 2020s; this is a MaraDNS 3.5 change, not a change to be done in the 3.4 branch. I *already* have enough changes to MaraDNS 3.4 to merit a 3.4.02 release (again, *no security bugs were found*, so this is a maintenance, not security update).

**Comment by samboy** [comment]
I have released a snapshot of Deadwood today:

https://maradns.samiam.org/deadwood/snap/deadwood-S-2019-11-11-1.tar.bz2

This snapshot updates the Windows documents in the Deadwood source code tarball.

Next: The Russian files on the MaraDNS side of things (yes, I agree making the Git code the one source of truth and deriving everything from that will make life easier all around).

**Comment by samboy** [comment]
See also: https://github.com/samboy/MaraDNS/commit/6f1e9b0344c8c9932756204c8eace8c0b13e5544

When I was making this update, I saw that the Windows reference file has a bunch of information which is inaccurate when describing the Windows port.

**Comment by samboy** [comment]
Not to mention: https://github.com/samboy/MaraDNS/commit/5b5c9088dedf4628824201c04de1465d9834dce9

(An error was made when making the patch by hand. Like I said, we will move on to one source of truth in the 2020s)

**Comment by samboy** [comment]
Done: http://maradns.samiam.org/download/3.4/snap/

The 2019-11-20 version now has the Russian translations.

**Comment by samboy** [comment]
I have implemented “One Source of Truth”: All versions of MaraDNS are now derived from the Git version.

**Comment by samboy** [comment]
See https://github.com/samboy/MaraDNS/issues/66
