### ISSUE TITLE
Future: Potencially drop python2 dependencies

### ISSUE THREAD

**Issue by ktrace** [samboy/MaraDNS#65]
bind2csv2.py potencially may run with python3.
For this we need sed -e "s/\(print\)\s\(.*\)$/\\1(\\2)/" to replace print "xxxx" -> print("xxx") and check strings
1227:			print("Error is on line " + str(linenum) ,)
1248:	print("Where {file list} is a list of files you want to make",)

After that bind2csv2.py seems may run both python2 & python3

**Comment by samboy** [comment]
python2 will be supported (in RedHat) until at least 2024, so even though official Python foundation support for python2 ends in January, this isn’t an urgent issue which needs to be fixed in the stable 3.4 branch.

I will do this in the future 3.5 branch.

**Comment by ktrace** [comment]
ok, but script with same changes will work _both_ in python 2 & 3. but if you think it's must be done late, let it be :)

**Comment by samboy** [comment]
The script is now a Python2/3 polyglot.  Note that the script doesn’t work with a good deal of zone files BIND can process, but it has been updated for the 2020s. 

These changes will *not* be part of the MaraDNS 3.4.02 release to be done early next year/decade.

**Comment by samboy** [comment]
Related discussion: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=936992

There was no reason to get so excited about bind2csv2.py.  It’s something I wrote 12 years ago, it’s not used for anything critical in core MaraDNS, and the Python foundation, if you asked me, should have solicited a patron to pay for the continued maintenance of Python2 (something RedHat will probably end up doing).

**Comment by samboy** [comment]
Locking conversation to avoid spam.
