### ISSUE TITLE
adding support for Stephen Black’s ad-blocking HOSTS file

### ISSUE THREAD

**Issue by arunsoman** [samboy/MaraDNS#69]
I am looking for a feature provided in pi-hole which blocks the internet ads in maraDNS, I am ready to contribute if you could point to the right direction, ie where to patch this new feature

**Comment by samboy** [comment]
OK, here you go: https://discourse.pi-hole.net/t/how-do-i-add-additional-block-lists-to-pi-hole/259

pi-hole *used* to keep their ad-lists.list file in GitHub. but they have moved it.

Here’s a list: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

So, to keep this reasonable, I think we can use Stephen Black’s list.

Now, a problem with Deadwood: Deadwood isn’t designed to store a list that large in a memory efficient method for putting on a Raspberry Pi. I can easily increase Deadwood’s maximum to allow up to 200,000 custom domains (Steve’s list is about 65,000 names):

* There will be a delay starting up deadwood processing that many entries
* It will, as a recall, take about two gigabytes to store that many entries

The trick is to use an in-memory database like sqlite or Tokyo Cabinet. But, that is something someone else can do. I’ll just make it a huge slow loading direct Deadwood huge list.

**Comment by samboy** [comment]
Here’s the GitHub page of that content: https://github.com/StevenBlack/hosts

**Comment by samboy** [comment]
I have made this possible.  Look for the script `make.blacklist.sh` which I have just added and run it as follows:

```
This is a command which will use Steven Black's blacklist to add
a large blacklist to Deadwood.  To use this script, on a UNIX-like
system (e.g. Linux, maybe MacOS), type in the following command from
the directory containing this:

mkdir /etc/deadwood/
mkdir /etc/deadwood/execfile/
./make.blacklist.sh > /etc/deadwood/execfile/blacklist

Once this "blacklist" file is created, add the following line to
the end of one's dwood3rc file:

execfile("blacklist")

Note that each entry takes over one kilobyte to store, so Deadwood 
needs about 70 megabytes to use this blacklist.
```

Implemented.  Closing this ticket.
