### ISSUE TITLE
Could not open hash at dw_cache_bin for reading

### ISSUE THREAD

**Issue by kaykamel** [samboy/MaraDNS#79]
I am getting this error when resolving .

[dwood3rc.txt](https://github.com/samboy/MaraDNS/files/4952016/dwood3rc.txt)

**Comment by samboy** [comment]
This is a non-fatal error which can be safely ignored. The cache file just keeps copies of previously resolved DNS names around between invocations of Deadwood; if the cache file can’t be read, then DNS resolution might be a bit slower for some names after starting up Deadwood, but everything will be OK.

Not a bug, closing.

**Comment by samboy** [comment]
MaraDNS 3.5.0008 makes this error message only visible if using a non-default value for `verbose_level` (10 or more). This message will no longer be visible for most users.
