### ISSUE TITLE
Does MaraDNS support DNS registration

### ISSUE THREAD

**Issue by DocEBrown** [samboy/MaraDNS#9]
My question is: In Windows we can set the network connection to 'Register this connection's address in DNS'. Does MaraDNS support this? And if so, how do I configure it and get it to work? If not, is there a way I can add that capability to my environment?

I have not found any reference to this on the MaraDNS site.

I am investigating using MaraDNS in a small non-profit library. I have gotten MaraDNS w/ DeadWood to work in my home test environment as a recursive server for the internet and able to resolve nodes for my local net using the local csv2 file. I am using DHCP from my router to configure many of the nodes (except the server and printers, for example). I am not using Active Directory or a Domain Controller.

**Comment by samboy** [comment]
If I understand the question correctly: Neither MaraDNS nor Deadwood have support for Multicast DNS nor Dynamic DNS.  There are no plans to add these features to MaraDNS at this time, so I will close this issue.
